/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyTokenPolygonMumbai } from "./MyTokenPolygonMumbai";
export * as factories from "./factories";
export { MyTokenPolygonMumbai__factory } from "./factories/MyTokenPolygonMumbai__factory";
