# Use root/example as user/password credentials
version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: web3-snippets
    restart: always
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: jake
      MYSQL_PASSWORD: jake
      MYSQL_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3306
    expose:
      - 3307


